### ISSUE TITLE
Loading modules from py27.exe's directory

### ISSUE THREAD

**Issue by cbm755** [manthey/pyexe#22]
Version 2.7.9.10 would load modules from the directory where "py.exe" lives, even if the $PWD was elsewhere.  This seems to be no longer the case with v11, v12 and v13.  Is that by design?  Assuming so, is manipulating $PYTHONPATH the best workaround?

Example: suppose I have:
```
/some/dir/py.exe
/some/dir/sympy/
```
And I'm currently in `/some/other/dir/` with `/some/dir/` in my $PATH.  Then `py.exe -c "import sympy"` fails.

**Comment by manthey** [comment]
The change was deliberate, but perhaps wasn't considered enough (and could or should be reconsidered).  Pedantically, the goal is to have pyexe behave as close to python that was installed in the standard way as possible.  Installed python adds its site-packages to the path.  For pyexe, adding its own path wouldn't be inappropriate.

**Comment by cbm755** [comment]
That makes sense.

Here is my half-hearted defense of this "feature": its a crude newbie-friendly mental model for setting up a self-contained python install: "anything I put in this directory with py.exe will be usable by py.exe".

For me, it allowed me to ship py.exe and a couple additional modules.  I can think of two alternatives:

1.  I build my own py.exe with my two additional modules baked in (appveyor makes this less daunting than before!)
2.  I configure $PYTHONPATH myself.  But my software can also use the CPython interpreter so I'll need Python-interpreter-specific configuration, when I really just want to call $PYTHON.

Have I missed any other obvious approaches?  How do you envision people shipping py.exe plus extras?

**Comment by manthey** [comment]
Digging into Python more, I will add back in pyexe's own path.  It is normally added as part of python's site.py module, but is diverted by pyinstaller.  Expect a PR soon.

pyexe supports pip installation via `pyexe -m pip install --target . <module>`.  If you leave off the `--target` option, installation goes to distutils' `get_python_lib` value, which is python's path plus `Lib\site-packages`.  Should distutils be monkey-patched to return pyexe's path in this instance?

**Comment by manthey** [comment]
@cbm755 You can try out the build artifacts from appveyor.  If these work for you, I'll merge PR #24 and then make a new release.

**Comment by cbm755** [comment]
Does you previous comment mean that I can arrange things as:
```
/some/dir/py.exe
/some/dir/Lib/site-packages/sympy/
```
and it will just work with v13?  If will try that later and also test #24...

**Comment by manthey** [comment]
It didn't, but I could make it so it does.  Currently, you can arrange things as:
```
/some/dir/py.exe
/some/dir/sympy
```
Also adding `Lib/site-packages` can easily be done.

I'm also still vacillating on whether there should be monkey patching so that `py.exe -m pip install <module>` would install to either `/some/dir` or `/some/dir/Lib/site-pacakages`.  It seems like if py.exe supports `Lib/site-packages`, so should the bundled pip module.

**Comment by cbm755** [comment]
Ok, I've done some tests.  Suppose `py27.exe` is in `/some/dir` and we are somewhere else with `/some/dir` in our path.

  * v13: `some/dir/` does not work (we knew this already).
  * v13: `some/dir/Lib/site-packages/` does *not* work.
  * #24: py27: `some/dir/` works!  :)
  * #24: py27: `some/dir/Lib/site-packages/` does *not* work.

**Comment by cbm755** [comment]
For pip, maybe `/some/dir/Lib/site-packages` is better?   That way, if someone just tosses py.exe in a directory with lots of other files, pip doesn't add lots of mysterious things.

**Comment by manthey** [comment]
@cbm755 I've added support for `Lib/site-packages`.  We'll leave pip and other issues to other PRs.
