### ISSUE TITLE
Functions in threads cannot always access globals

### ISSUE THREAD

**Issue by kbickar** [manthey/pyexe#40]
Functions in threads are not always able to read global variables:

For example, the code:
```python
import threading

def threaded_func():
    print a

a = 1
threading.Thread(target=threaded_func).start()
``` 
Should print just "1", but instead prints the error:

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "<string>", line 4, in threaded_func
NameError: global name 'a' is not defined
```

Interestingly, running the program again will sometime yield the correct results

**Comment by manthey** [comment]
Python explicitly joins all non-daemon threads on shutdown.  If you have a non-daemon thread that never finishes, python won't terminate.  Adding an explicit join is just a work-around for py.exe until there is a fix.
